import snakemake_staging
from snakemake_staging.stages import NoOpStage

stage = NoOpStage("stage", config)

rule a:
    output:
        stage.staged("output/a.txt")
    shell:
        """
        mkdir -p output
        echo "test" > {output}
        """

include:
    snakemake_staging.snakefile()
